language: java
jdk:
- openjdk7
- oraclejdk8
- oraclejdk7
script: mvn install -B -V
notifications:
  slack:
    rooms:
    - secure: Q8SMQchcShvX4EVggGhrAfucG/8ihNa+uErOS35tKcsgLpd+sf3UETmJLaIixbLjVHRERYb5qtAsrRYwbFBObRXvfHJk2INJh33NnIjA32ObBp0IcwlXQ7FQTBG9IYgj9IJU1tJ9/DNa0Xco6SaziRkvr5EMtFLoa24HsAQxTxDHmnBz2BAq/Elw6/H6/BdsIaZ2sgP3wx3mKlIz988RjP9bYqWaAu81JqPAuEc0FMDobt814zxqomzDpzJQuSW12PzVA32eAa3T1tq43GeeWzOJ9vmtykknTiF+1SYTBhCCprKhWGb5pag91bGE0Bw51XsVc8tPh4WhHh84Bc2DPZAavohBupUAejZGADp/+G0hhOBtKLFsYrOhI8UfFzEXwuc92PR2Mi1dwb0iEax675OXiHTKe+Qw7YuSQHX+H1ADod8kmxlL1ARHKRvqnwuzcilIASNAJH2XanwROwWazZDJePQuATSIObX6kHbk3wG3JsXFGYdOGYmjlJwZz1WjyRRwcs4QlaMGxUft/PkF+02UCw8r7Boo8OCWO8knACt4MWqjtOoHTaddvWLvd2DMTNr4XZVQJAgQCjb8hf+4oBJ2qp03RQXaDusyLM5+cZxi741ufa0pQUi5Ijm0RWlxHv5juta1WPRTS8KWFOyum+bLr1vnO/zUrYuMR7WlaRE=
deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  file: release/*
  on:
    tags: true
  api_key:
    secure: ZbzP2lo+PET6sRnQ57EfqSRGxUgas06VURimyJi47uOBtGrWpsQ8MF6o4wm+4IHnGmkj5NIIRBychTur+BVUnDjLHK1kSW4bI3a3UkYWTvDjfhvTHhabXO5ND7j/ffI/LMRHA+pJst1TOJOiP4bmK9wTYwsRaOFhQvGUZH1VbHwpIqyBpdK+7utoOCiyi65mGKFQZXVb45DzFjRYuylr1eU3+znWAc/vq8dNs8PjG4ngE5cTPSbwleHGiccyrE8KqK3B+M4chKcknzp8Mbhb7BiA8dVxZIGkv7iF+cxcuiVMHwNKbVmbt8Vwj1PtEVr+sbDzUh9rSDDlKzDFcNrDCm4n4gIyjkiP9A7cCf8kQkYfCHChjN30scz1GyK+vd/Jr+NnWzZVl/IcQuKOnpxG7SVmrOWMitzgj1Kt/rrMIqfdE9CuItgxLRmPX9kltb2QtUfn+It90qWUf+PQrJ8xk37LK2mrSHWIssOHDCNljTnzxWdsDWk1HBFlwUtrRNGXr/F/jeJB06lY8KZiBWGeTAJlx6AvskJ08ACSlXaRqzvzjcE3qZrSGzF0t96zh9I+o9VkPTsdxd5zbFy9daRJCZwbQoFP8KQH0z93uSE8lvcx0nt3xEP5UvpgXynNHsklFiRMOi6ywaUkXG7FEL6vgGej/Eo4Ord9t1nxYij6lfg=
